In [122]:
import pandas as pd
import numpy as np
import os

In [207]:
data = pd.read_csv(r'cars.csv')
data

,Name,Price,Vin Number,Vehicle Summary,Top features & Specs
0,2018 GMC Sierra 1500,"$36,990",3GTU2NEC8JG446325,"75,801 miles, automatic transmission, four whe...",NaN
1,2017 Ford C-Max Energi,"$13,990",1FADP5EUXHL104632,"40,545 miles, automatic transmission, front wh...","Keyless Entry, Tilt & Telescoping Wheel"
2,2019 Chevrolet Silverado 1500,"$37,999",1GCRYEED4KZ200547,"50,192 miles, automatic transmission, four whe...","Keyless Entry, Remote Start, Steering Wheel Co..."
3,2016 GMC Sierra 1500,"$40,499",3GTU2NEC2GG149866,"49,164 miles, automatic transmission, four whe...","Heated Seats, Navigation System, Remote Keyles..."
4,2018 Chevrolet Colorado,"$34,499",1GCPTDE10J1116888,"48,506 miles, automatic transmission, four whe...","Auto Climate Control, Heated Seats, Navigation..."
...,...,...,...,...,...
5172,2018 Subaru Outback,"$25,590",4S4BSAACXJ3289210,"34,791 miles, automatic transmission, all whee...","ABS (4-Wheel), AM/FM Stereo, Air Conditioning,..."
5173,2013 Chevrolet Corvette,"$37,590",1G1YE3DWXD5100242,"9,751 miles, automatic transmission, rear whee...","Keyless Start, Fog Lights"
5174,2017 Mercedes-Benz GLC-Class,"$48,499",WDC0G6EB4HF220057,"18,759 miles, automatic transmission, all whee...","Heated Seats, Navigation System, Seat Memory, ..."
5175,2015 Ford Taurus,"$19,990",1FAHP2E80FG207387,"17,044 miles, automatic transmission, front wh...","Keyless Entry, Tilt & Telescoping Wheel, Bluet..."
5176,2017 FIAT 124 Spider,"$26,590",JC1NFAEK5H0105145,"5,414 miles, automatic transmission, rear whee...","Heated Seats, Keyless Start, Bluetooth Wireles..."

In [208]:
data2 = data.copy()

In [209]:
null_values = data.isnull().sum()
null_values

Name                     24
Price                    24
Vin Number               24
Vehicle Summary          24
Top features & Specs    215
dtype: int64

In [210]:
exel = data.to_excel('cars.xlsx')

In [213]:
df = pd.read_excel('cars.xlsx')
df.drop(columns = "Unnamed: 0", inplace=True, axis=1)

In [217]:
df.to_excel('cars.xlsx')

In [218]:
df

,Name,Price,Vin Number,Vehicle Summary,Top features & Specs
0,2018 GMC Sierra 1500,"$36,990",3GTU2NEC8JG446325,"75,801 miles, automatic transmission, four whe...",NaN
1,2017 Ford C-Max Energi,"$13,990",1FADP5EUXHL104632,"40,545 miles, automatic transmission, front wh...","Keyless Entry, Tilt & Telescoping Wheel"
2,2019 Chevrolet Silverado 1500,"$37,999",1GCRYEED4KZ200547,"50,192 miles, automatic transmission, four whe...","Keyless Entry, Remote Start, Steering Wheel Co..."
3,2016 GMC Sierra 1500,"$40,499",3GTU2NEC2GG149866,"49,164 miles, automatic transmission, four whe...","Heated Seats, Navigation System, Remote Keyles..."
4,2018 Chevrolet Colorado,"$34,499",1GCPTDE10J1116888,"48,506 miles, automatic transmission, four whe...","Auto Climate Control, Heated Seats, Navigation..."
...,...,...,...,...,...
5172,2018 Subaru Outback,"$25,590",4S4BSAACXJ3289210,"34,791 miles, automatic transmission, all whee...","ABS (4-Wheel), AM/FM Stereo, Air Conditioning,..."
5173,2013 Chevrolet Corvette,"$37,590",1G1YE3DWXD5100242,"9,751 miles, automatic transmission, rear whee...","Keyless Start, Fog Lights"
5174,2017 Mercedes-Benz GLC-Class,"$48,499",WDC0G6EB4HF220057,"18,759 miles, automatic transmission, all whee...","Heated Seats, Navigation System, Seat Memory, ..."
5175,2015 Ford Taurus,"$19,990",1FAHP2E80FG207387,"17,044 miles, automatic transmission, front wh...","Keyless Entry, Tilt & Telescoping Wheel, Bluet..."
5176,2017 FIAT 124 Spider,"$26,590",JC1NFAEK5H0105145,"5,414 miles, automatic transmission, rear whee...","Heated Seats, Keyless Start, Bluetooth Wireles..."